# Generated by Django 5.2.5 on 2025-08-29 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('room_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_participants', models.IntegerField(default=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='userpresence',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpresence',
            name='current_language',
        ),
        migrations.RemoveField(
            model_name='userpresence',
            name='user',
        ),
        migrations.CreateModel(
            name='ConferenceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chat.conferenceroom')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ru', 'Russian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ar', 'Arabic'), ('hi', 'Hindi')], default='en', max_length=10)),
                ('is_speaking', models.BooleanField(default=False)),
                ('is_online', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.conferenceroom')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('name', 'room')},
            },
        ),
        migrations.CreateModel(
            name='VoiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('original_audio_file', models.FileField(upload_to='voice_messages/')),
                ('original_text', models.TextField()),
                ('detected_language', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_messages', to='chat.conferenceroom')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_messages', to='chat.participant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TranslatedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('translated_audio_file', models.FileField(blank=True, null=True, upload_to='translated_audio/')),
                ('translation_status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_translations', to='chat.participant')),
                ('voice_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='chat.voicemessage')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('voice_message', 'target_participant')},
            },
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='UserPresence',
        ),
    ]
